# Generated by GitHub Copilot (GPT-5)
# Multi-stage Dockerfile for Google Maps Timeline Viewer
# Supports both x86_64 (amd64) and ARM64 (Apple Silicon, Raspberry Pi) architectures
# Stage 1: Builder - Install dependencies with native compilation
# Stage 2: Runtime - Lightweight image with Node.js + Caddy

# ============================================================================
# Stage 1: Builder
# ============================================================================
FROM --platform=$BUILDPLATFORM node:20-slim AS builder

# Install build dependencies for native modules (sharp, better-sqlite3)
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# ============================================================================
# Stage 2: Runtime
# ============================================================================
FROM node:20-slim

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    libvips-dev \
    curl \
    ca-certificates \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# Install Caddy
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && \
    echo 'deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main' | tee /etc/apt/sources.list.d/caddy-stable.list && \
    apt-get update && apt-get install -y caddy && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy node modules from builder
COPY --from=builder /build/node_modules ./node_modules

# Copy application files
COPY package*.json ./
COPY server ./server
COPY scripts ./scripts
COPY public ./public
COPY Caddyfile ./Caddyfile

# Create data directory
RUN mkdir -p /data/logs /data/photos /data/timeline

# Copy startup script
COPY docker/start.sh ./start.sh
RUN chmod +x ./start.sh

# Set environment variables
ENV NODE_ENV=production
ENV DATA_DIR=/data
ENV PORT=3000

# Expose port
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD curl -f http://localhost:3000/health || exit 1

# Start both Node.js and Caddy
CMD ["./start.sh"]
