/**
 * Generated by GitHub Copilot (GPT-5)
 * SSE Prefetch progress tests.
 * Starts server, triggers a prefetch with mock place IDs and listens to initial SSE packet.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const PORT = 43112;
let child;
let DATA_DIR;

async function waitForHealth(baseUrl) {
  for (let i = 0; i < 40; i++) {
    try {
      const r = await fetch(`${baseUrl}/health`);
      if (r.ok) return;
    } catch {}
    await new Promise(r => setTimeout(r, 200));
  }
  throw new Error('Health check failed');
}

test('setup server for SSE tests', async (t) => {
  DATA_DIR = mkdtempSync(join(tmpdir(), 'timeline-viewer-sse-'));
  child = spawn(process.execPath, ['server/api.js'], {
    env: { ...process.env, PORT: String(PORT), DATA_DIR, NODE_ENV: 'test', DAILY_API_QUOTA: '999999', LOG_LEVEL: 'error' },
    stdio: ['ignore', 'pipe', 'pipe']
  });
  t.after(() => {
    try { child.kill('SIGTERM'); } catch {}
    try { rmSync(DATA_DIR, { recursive: true, force: true }); } catch {}
  });
  await waitForHealth(`http://127.0.0.1:${PORT}`);
  assert.ok(true);
});

// Note: Since no timeline data exists, prefetch with fake IDs. API will attempt fetch and likely error but should update progress state.
// We expect immediate SSE initial payload.

test('SSE prefetch progress initial event', async () => {
  const resp = await fetch(`http://127.0.0.1:${PORT}/api/prefetch/progress`);
  assert.equal(resp.status, 200);
  const reader = resp.body.getReader();
  const { value } = await reader.read();
  assert.ok(value);
  const text = new TextDecoder().decode(value);
  assert.match(text, /data: {/);
});

