/**
 * Generated by GitHub Copilot (GPT-5)
 * SSE Prefetch progress tests.
 * Tests the prefetch progress endpoint directly using supertest.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { mkdtempSync, rmSync, mkdirSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// Set test mode before importing app
process.env.TEST_MODE = 'true';
process.env.NODE_ENV = 'test';
process.env.LOG_LEVEL = 'error';

import { app, initializeApp } from '../server/api.js';

let DATA_DIR;

test('setup app for SSE tests', async (t) => {
  DATA_DIR = mkdtempSync(join(tmpdir(), 'timeline-viewer-sse-'));
  const photosDir = join(DATA_DIR, 'photos');
  if (!existsSync(photosDir)) mkdirSync(photosDir, { recursive: true });

  process.env.DATA_DIR = DATA_DIR;
  process.env.NODE_ENV = 'test';
  process.env.DAILY_API_QUOTA = '999999';

  // Initialize app with graceful error handling
  try {
    await initializeApp();
  } catch (error) {
    if (process.env.TEST_MODE !== 'true') throw error;
  }

  t.after(() => {
    try { rmSync(DATA_DIR, { recursive: true, force: true }); } catch {}
  });

  assert.ok(true, 'App initialized for SSE tests');
});

test('GET /api/prefetch/progress returns SSE stream', async () => {
  const response = await request(app)
    .get('/api/prefetch/progress')
    .expect(200);

  // Check response has SSE content-type
  assert.ok(response.headers['content-type'].includes('text/event-stream'));
});
