/**
 * Generated by GitHub Copilot (GPT-5)
 *
 * Basic API server integration tests using Node's built-in test runner.
 * These tests spawn the Express server in a child process with an isolated
 * temporary DATA_DIR to avoid interfering with real caches.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync, mkdirSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';

// Choose a high, unlikely-to-conflict port
const PORT = process.env.TEST_PORT ? Number(process.env.TEST_PORT) : 43111;

let child;
let DATA_DIR;

async function waitForHealth(baseUrl, attempts = 40, intervalMs = 250) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(`${baseUrl}/health`, { cache: 'no-store' });
      if (res.ok) {
        const body = await res.json();
        if (body && body.status === 'ok') return true;
      }
    } catch (e) {
      lastErr = e;
    }
    await delay(intervalMs);
  }
  throw lastErr ?? new Error('Server did not become healthy');
}

test('setup: spawn API server', async (t) => {
  // Create isolated data directory
  DATA_DIR = mkdtempSync(join(tmpdir(), 'timeline-viewer-test-'));
  const photosDir = join(DATA_DIR, 'photos');
  if (!existsSync(photosDir)) mkdirSync(photosDir, { recursive: true });

  child = spawn(process.execPath, ['server/api.js'], {
    env: {
      ...process.env,
      NODE_ENV: 'test',
      PORT: String(PORT),
      DATA_DIR,
      LOG_LEVEL: 'warn',
      // Ensure we never accidentally call external APIs during these tests
      DAILY_API_QUOTA: '0'
    },
    stdio: ['ignore', 'pipe', 'pipe']
  });

  // Pipe logs in case of failure
  child.stdout.on('data', (d) => {
    if (process.env.VERBOSE_TESTS) process.stdout.write(d);
  });
  child.stderr.on('data', (d) => {
    if (process.env.VERBOSE_TESTS) process.stderr.write(d);
  });

  // Cleanup on test end
  t.after(() => {
    try { child?.kill('SIGTERM'); } catch {}
    try { rmSync(DATA_DIR, { recursive: true, force: true }); } catch {}
  });

  await waitForHealth(`http://127.0.0.1:${PORT}`);
  assert.ok(true, 'Server healthy');
});

test('GET /health returns ok', async () => {
  const res = await fetch(`http://127.0.0.1:${PORT}/health`);
  assert.equal(res.status, 200);
  const body = await res.json();
  assert.equal(body.status, 'ok');
  assert.ok(body.timestamp);
});

test('GET /api/timeline/list returns array', async () => {
  const res = await fetch(`http://127.0.0.1:${PORT}/api/timeline/list`);
  assert.equal(res.status, 200);
  const body = await res.json();
  assert.ok(Array.isArray(body));
});

test('GET /api/stats returns expected shape', async () => {
  const res = await fetch(`http://127.0.0.1:${PORT}/api/stats`);
  assert.equal(res.status, 200);
  const body = await res.json();
  assert.ok(body.apiUsage);
  assert.ok(typeof body.apiUsage.today === 'number');
  assert.ok(body.cache);
  assert.ok(typeof body.cache.placesCount === 'number');
  assert.ok(body.photos);
});
