#!/bin/bash

# Generated by GitHub Copilot using Claude Sonnet 4.5
# Startup script for Docker container
# Starts both Node.js API server and Caddy web server

set -e

echo "Starting Google Maps Timeline Viewer..."

# Start Node.js server in background
echo "Starting Node.js API server on port ${PORT}..."
node server/api.js &
NODE_PID=$!

# Wait a moment for Node.js to start
sleep 2

# Check if Node.js started successfully
if ! kill -0 $NODE_PID 2>/dev/null; then
    echo "ERROR: Node.js server failed to start"
    exit 1
fi

echo "Node.js API server started (PID: $NODE_PID)"

# Start Caddy web server
echo "Starting Caddy web server on port 8080..."
caddy run --config /app/Caddyfile --adapter caddyfile &
CADDY_PID=$!

# Wait a moment for Caddy to start
sleep 2

# Check if Caddy started successfully
if ! kill -0 $CADDY_PID 2>/dev/null; then
    echo "ERROR: Caddy server failed to start"
    kill $NODE_PID 2>/dev/null || true
    exit 1
fi

echo "Caddy web server started (PID: $CADDY_PID)"
echo "Application is ready!"
echo "Access the application at http://localhost:8080"

# Function to handle shutdown
shutdown() {
    echo "Shutting down..."
    kill $CADDY_PID 2>/dev/null || true
    kill $NODE_PID 2>/dev/null || true
    wait $CADDY_PID 2>/dev/null || true
    wait $NODE_PID 2>/dev/null || true
    echo "Shutdown complete"
    exit 0
}

# Trap shutdown signals
trap shutdown SIGTERM SIGINT

# Wait for either process to exit
wait -n $NODE_PID $CADDY_PID

# If we get here, one process died
echo "A process has exited unexpectedly"
shutdown
