/**
 * Generated by GitHub Copilot (Claude Haiku 4.5)
 * 
 * Mock database for testing
 * Provides in-memory implementation of database functions without native modules
 */

const mockData = {
  places: new Map(),
  photos: new Map(),
  timelineFiles: new Map(),
  apiUsage: { count: 0, quota_limit: 5000, date: new Date().toISOString().split('T')[0] }
};

export async function initDatabase() {
  // No-op for testing
  return null;
}

export function getDatabase() {
  // Return mock database object
  return {
    prepare: (sql) => ({
      get: () => ({ count: 0 }),
      run: () => ({ changes: 0 })
    })
  };
}

export function getCachedPlace(placeId) {
  return mockData.places.get(placeId) || null;
}

export function setCachedPlace(placeId, data) {
  mockData.places.set(placeId, { ...data, cached_at: Date.now() });
}

export function getCachedPhoto(placeId, size) {
  const key = `${placeId}_${size}`;
  return mockData.photos.get(key) || null;
}

export function setCachedPhoto(placeId, size, data) {
  const key = `${placeId}_${size}`;
  mockData.photos.set(key, { ...data, cached_at: Date.now() });
}

export function getTimelineFiles() {
  return Array.from(mockData.timelineFiles.values());
}

export function getActiveTimeline() {
  return null;
}

export function addTimelineFile(id, filename) {
  mockData.timelineFiles.set(id, { id, filename });
}

export function setActiveTimeline(id) {
  // No-op for testing
}

export function getTodayApiUsage() {
  return mockData.apiUsage;
}

export function incrementApiUsage() {
  mockData.apiUsage.count++;
}

export function isQuotaExceeded() {
  return mockData.apiUsage.count >= mockData.apiUsage.quota_limit;
}

export function getAllCachedPlaceIds() {
  return Array.from(mockData.places.keys());
}

export function closeDatabase() {
  // No-op for testing
}
